# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import semantic_memory_pb2 as semantic__memory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in semantic_memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticMemoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embedding = channel.unary_unary(
                '/semantic_memory.SemanticMemory/Embedding',
                request_serializer=semantic__memory__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=semantic__memory__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.Rerank = channel.unary_unary(
                '/semantic_memory.SemanticMemory/Rerank',
                request_serializer=semantic__memory__pb2.RerankRequest.SerializeToString,
                response_deserializer=semantic__memory__pb2.RerankResponse.FromString,
                _registered_method=True)
        self.RerankQwen = channel.unary_unary(
                '/semantic_memory.SemanticMemory/RerankQwen',
                request_serializer=semantic__memory__pb2.RerankRequest.SerializeToString,
                response_deserializer=semantic__memory__pb2.RerankResponse.FromString,
                _registered_method=True)
        self.RetrieveAndRerank = channel.unary_unary(
                '/semantic_memory.SemanticMemory/RetrieveAndRerank',
                request_serializer=semantic__memory__pb2.RetrieveAndRerankRequest.SerializeToString,
                response_deserializer=semantic__memory__pb2.RetrieveAndRerankResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/semantic_memory.SemanticMemory/Health',
                request_serializer=semantic__memory__pb2.HealthRequest.SerializeToString,
                response_deserializer=semantic__memory__pb2.HealthResponse.FromString,
                _registered_method=True)


class SemanticMemoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Embedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RerankQwen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveAndRerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticMemoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embedding': grpc.unary_unary_rpc_method_handler(
                    servicer.Embedding,
                    request_deserializer=semantic__memory__pb2.EmbeddingRequest.FromString,
                    response_serializer=semantic__memory__pb2.EmbeddingResponse.SerializeToString,
            ),
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=semantic__memory__pb2.RerankRequest.FromString,
                    response_serializer=semantic__memory__pb2.RerankResponse.SerializeToString,
            ),
            'RerankQwen': grpc.unary_unary_rpc_method_handler(
                    servicer.RerankQwen,
                    request_deserializer=semantic__memory__pb2.RerankRequest.FromString,
                    response_serializer=semantic__memory__pb2.RerankResponse.SerializeToString,
            ),
            'RetrieveAndRerank': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveAndRerank,
                    request_deserializer=semantic__memory__pb2.RetrieveAndRerankRequest.FromString,
                    response_serializer=semantic__memory__pb2.RetrieveAndRerankResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=semantic__memory__pb2.HealthRequest.FromString,
                    response_serializer=semantic__memory__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semantic_memory.SemanticMemory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('semantic_memory.SemanticMemory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticMemory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_memory.SemanticMemory/Embedding',
            semantic__memory__pb2.EmbeddingRequest.SerializeToString,
            semantic__memory__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_memory.SemanticMemory/Rerank',
            semantic__memory__pb2.RerankRequest.SerializeToString,
            semantic__memory__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RerankQwen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_memory.SemanticMemory/RerankQwen',
            semantic__memory__pb2.RerankRequest.SerializeToString,
            semantic__memory__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveAndRerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_memory.SemanticMemory/RetrieveAndRerank',
            semantic__memory__pb2.RetrieveAndRerankRequest.SerializeToString,
            semantic__memory__pb2.RetrieveAndRerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_memory.SemanticMemory/Health',
            semantic__memory__pb2.HealthRequest.SerializeToString,
            semantic__memory__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
