# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: semantic_memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'semantic_memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15semantic_memory.proto\x12\x0fsemantic_memory\"4\n\x10\x45mbeddingRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x11\n\tnormalize\x18\x02 \x01(\x08\":\n\x11\x45mbeddingResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\x12\x11\n\tdimension\x18\x02 \x01(\x05\"U\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\x13\n\x0binstruction\x18\x04 \x01(\t\"B\n\x0eRerankResponse\x12\x30\n\x07results\x18\x01 \x03(\x0b\x32\x1f.semantic_memory.RankedDocument\"<\n\x0eRankedDocument\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"c\n\x18RetrieveAndRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\x16\n\x0eretrieve_top_k\x18\x04 \x01(\x05\"g\n\x19RetrieveAndRerankResponse\x12\x30\n\x07results\x18\x01 \x03(\x0b\x32\x1f.semantic_memory.RankedDocument\x12\x18\n\x10total_latency_ms\x18\x02 \x01(\x02\"\x0f\n\rHealthRequest\"2\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xb5\x03\n\x0eSemanticMemory\x12R\n\tEmbedding\x12!.semantic_memory.EmbeddingRequest\x1a\".semantic_memory.EmbeddingResponse\x12I\n\x06Rerank\x12\x1e.semantic_memory.RerankRequest\x1a\x1f.semantic_memory.RerankResponse\x12M\n\nRerankQwen\x12\x1e.semantic_memory.RerankRequest\x1a\x1f.semantic_memory.RerankResponse\x12j\n\x11RetrieveAndRerank\x12).semantic_memory.RetrieveAndRerankRequest\x1a*.semantic_memory.RetrieveAndRerankResponse\x12I\n\x06Health\x12\x1e.semantic_memory.HealthRequest\x1a\x1f.semantic_memory.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semantic_memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=42
  _globals['_EMBEDDINGREQUEST']._serialized_end=94
  _globals['_EMBEDDINGRESPONSE']._serialized_start=96
  _globals['_EMBEDDINGRESPONSE']._serialized_end=154
  _globals['_RERANKREQUEST']._serialized_start=156
  _globals['_RERANKREQUEST']._serialized_end=241
  _globals['_RERANKRESPONSE']._serialized_start=243
  _globals['_RERANKRESPONSE']._serialized_end=309
  _globals['_RANKEDDOCUMENT']._serialized_start=311
  _globals['_RANKEDDOCUMENT']._serialized_end=371
  _globals['_RETRIEVEANDRERANKREQUEST']._serialized_start=373
  _globals['_RETRIEVEANDRERANKREQUEST']._serialized_end=472
  _globals['_RETRIEVEANDRERANKRESPONSE']._serialized_start=474
  _globals['_RETRIEVEANDRERANKRESPONSE']._serialized_end=577
  _globals['_HEALTHREQUEST']._serialized_start=579
  _globals['_HEALTHREQUEST']._serialized_end=594
  _globals['_HEALTHRESPONSE']._serialized_start=596
  _globals['_HEALTHRESPONSE']._serialized_end=646
  _globals['_SEMANTICMEMORY']._serialized_start=649
  _globals['_SEMANTICMEMORY']._serialized_end=1086
# @@protoc_insertion_point(module_scope)
